import QRCode from "qrcode";
import * as XLSX from "xlsx";

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const load=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));
let equipment=load("maintenpro.equipment",[]),orders=load("maintenpro.orders",[]),plans=load("maintenpro.plans",[]),team=load("maintenpro.team",[]);
let settings=load("maintenpro.settings",{appName:"MaintenPro",companyName:"",ownerEmail:"",driveName:"",language:"es",currency:"EUR",tax:21,alertDays:7,urgentDays:2,notifications:true});
let currentScreen="home",historyStack=[],detailId="",orderFilter="all";
const titles={home:"Mantenimiento profesional",equipment:"Equipos",equipmentForm:"Nuevo equipo",workForm:"Nueva avería",orders:"Órdenes de trabajo",plans:"Preventivos",calendar:"Calendario",orderDetail:"Detalle de orden",assistant:"Asistente técnico",reports:"Informes",settings:"Configuración",team:"Equipo técnico",help:"Ayuda"};
const uid=()=>crypto.randomUUID(),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const save=()=>{localStorage.setItem("maintenpro.equipment",JSON.stringify(equipment));localStorage.setItem("maintenpro.orders",JSON.stringify(orders));localStorage.setItem("maintenpro.plans",JSON.stringify(plans));localStorage.setItem("maintenpro.team",JSON.stringify(team));renderAll();};
const equip=id=>equipment.find(x=>x.id===id),money=n=>new Intl.NumberFormat(settings.language,{style:"currency",currency:settings.currency}).format(Number(n||0));
const fmtDate=v=>v?new Intl.DateTimeFormat(settings.language,{dateStyle:"medium"}).format(new Date(`${v}T12:00:00`)):"Sin fecha";
const days=v=>v?Math.ceil((new Date(`${v}T12:00:00`)-new Date())/86400000):9999;
function toast(t){const el=$("#toast");el.textContent=t;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200);}
const android=()=>window.MaintenProAndroid;
function connectDrive(){if(android()?.chooseDriveFolder){android().chooseDriveFolder();toast("Selecciona una ubicación en Google Drive");}else toast("Instala la app Android para conectar Drive");}
window.onMaintenProDriveReady=name=>{settings.driveName=name||"MaintenPro";localStorage.setItem("maintenpro.settings",JSON.stringify(settings));$("#onboarding").classList.add("hidden");applySettings();toast("Carpetas creadas correctamente");};
window.onMaintenProDriveError=message=>toast(message||"No se pudo preparar Drive");
window.onMaintenProSubscription=(active,price,message)=>{if(price)$("#subscriptionPrice").textContent=`${price} al mes`;$("#subscriptionStatus").textContent=active?"Suscripción mensual activa":(message||"Suscripción necesaria");$("#paywall").classList.toggle("hidden",!!active);if(active&&!settings.ownerEmail)$("#onboarding").classList.remove("hidden");};
window.onMaintenProPurchaseError=message=>toast(message||"No se pudo completar la compra");
$("#subscribeBtn").onclick=()=>android()?.subscribeMonthly?android().subscribeMonthly():toast("La suscripción se activa desde Google Play");
$("#restorePurchase").onclick=()=>android()?.restorePurchases?android().restorePurchases():toast("Abre la app instalada desde Google Play");
$("#manageSubscription").onclick=()=>android()?.manageSubscription?android().manageSubscription():toast("Gestiona la suscripción desde Google Play");
$("#connectDrive").onclick=connectDrive;
function go(screen,push=true){if(push&&screen!==currentScreen)historyStack.push(currentScreen);currentScreen=screen;$$(".screen").forEach(x=>x.classList.toggle("active",x.dataset.screen===screen));$("#screenTitle").textContent=titles[screen]||"MaintenPro";$("#backBtn").classList.toggle("hidden",screen==="home");$$(".bottom-nav button").forEach(x=>x.classList.toggle("active",x.dataset.go===screen));renderAll();scrollTo(0,0);}
function back(){go(historyStack.pop()||"home",false);}
$("#backBtn").onclick=back;$$("[data-back]").forEach(b=>b.onclick=back);$$("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));window.onAndroidBack=()=>{if(currentScreen==="home")return false;back();return true;};

async function fileData(input){const f=input?.files?.[0];if(!f)return"";if(f.size>1200000){toast("La imagen es demasiado grande; usa una fotografía más pequeña");return"";}return new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.readAsDataURL(f);});}
$("#equipmentForm").onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,d=Object.fromEntries(new FormData(form));delete d.photo;d.photo=await fileData(form.elements.photo);if(equipment.some(x=>x.code.toLowerCase()===d.code.trim().toLowerCase()))return toast("Ese código ya existe");equipment.unshift({...d,id:uid(),createdAt:new Date().toISOString()});save();form.reset();toast("Equipo guardado");go("equipment");};
$("#workForm").onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,d=Object.fromEntries(new FormData(form));delete d.photo;d.photo=await fileData(form.elements.photo);orders.unshift({...d,id:uid(),type:"Correctivo",createdAt:new Date().toISOString(),closedAt:"",resolution:"",parts:"",laborCost:0,partsCost:0});save();form.reset();toast("Orden correctiva creada");go("orders");};
$("#planForm").onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));plans.unshift({...d,id:uid(),createdAt:new Date().toISOString()});save();e.currentTarget.reset();toast("Plan preventivo creado");};
$("#teamForm").onsubmit=e=>{e.preventDefault();if(team.length>=3)return toast("Ya hay tres técnicos invitados");const d=Object.fromEntries(new FormData(e.currentTarget));if(team.some(x=>x.email.toLowerCase()===d.email.toLowerCase()))return toast("Ese correo ya está añadido");team.push({...d,id:uid()});save();e.currentTarget.reset();toast("Técnico añadido");};
$("#onboardingForm").onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));settings={...settings,...d};localStorage.setItem("maintenpro.settings",JSON.stringify(settings));connectDrive();};

function renderMetrics(){$("#mEquipment").textContent=equipment.length;$("#mOpen").textContent=orders.filter(x=>!x.closedAt).length;$("#mDue").textContent=plans.filter(x=>{const d=days(x.nextDate);return d>=0&&d<=7}).length;}
function empty(t){return`<div class="empty"><p>${t}</p></div>`;}
function renderEquipment(filter=""){const q=filter.toLowerCase();const rows=equipment.filter(x=>[x.name,x.code,x.site,x.area,x.location].join(" ").toLowerCase().includes(q));$("#equipmentList").innerHTML=rows.length?rows.map(x=>`<article class="equipment-card"><div class="equipment-photo">${x.photo?`<img src="${x.photo}">`:"⚙"}</div><div><b>${esc(x.name)}</b><small>${esc(x.code)} · ${esc(x.site||"Sin centro")} · ${esc(x.location||"Sin ubicación")}</small><span class="badge ${x.criticality==="Crítica"?"danger":""}">${esc(x.status)} · ${esc(x.criticality)}</span></div><div class="vertical"><button class="mini" data-qr="${x.id}">QR</button><button class="mini" data-break="${x.id}">Avería</button></div></article>`).join(""):empty("Añade tu primera máquina o equipo.");bindEquipmentActions();}
$("#equipmentSearch").oninput=e=>renderEquipment(e.target.value);
function fillEquipmentSelects(){[$("#workEquipment"),$("#planEquipment"),$("#assistantEquipment")].filter(Boolean).forEach(s=>{const value=s.value;s.innerHTML=`<option value="">${s.id==="assistantEquipment"?"Equipo no registrado":"Seleccionar equipo"}</option>`+equipment.map(x=>`<option value="${x.id}">${esc(x.code)} · ${esc(x.name)}</option>`).join("");s.value=value;});}
function bindEquipmentActions(){$$("[data-break]").forEach(b=>b.onclick=()=>{$("#workEquipment").value=b.dataset.break;go("workForm")});$$("[data-qr]").forEach(b=>b.onclick=()=>showQr(equip(b.dataset.qr)));}
async function showQr(e){const img=await QRCode.toDataURL(JSON.stringify({app:"MaintenPro",equipmentId:e.id,code:e.code}),{width:500,margin:1});const w=open("","_blank");w.document.write(`<html><head><title>QR ${esc(e.code)}</title><style>body{font-family:Arial;text-align:center;padding:25px}img{width:280px}button{padding:12px}</style></head><body><h2>${esc(e.name)}</h2><img src="${img}"><p>${esc(e.code)} · ${esc(e.location||"")}</p><button onclick="print()">Imprimir QR</button></body></html>`);w.document.close();toast("QR generado; al cerrar volverás a MaintenPro");}

function renderOrders(){let rows=orders;if(orderFilter==="open")rows=rows.filter(x=>!x.closedAt);if(orderFilter==="done")rows=rows.filter(x=>x.closedAt);$("#orderList").innerHTML=rows.length?rows.map(x=>{const e=equip(x.equipmentId);return`<article class="order-card"><span class="priority ${x.priority?.toLowerCase()}"></span><div><b>${esc(e?.name||"Equipo eliminado")}</b><small>${esc(x.type)} · ${esc(x.priority)} · ${fmtDate(x.dueDate)}</small><p>${esc(x.description)}</p><span class="badge ${x.closedAt?"done":""}">${x.closedAt?"Finalizada":esc(x.status)}</span></div><button class="mini" data-order="${x.id}">Abrir</button></article>`}).join(""):empty("No hay órdenes en esta vista.");$$("[data-order]").forEach(b=>b.onclick=()=>{detailId=b.dataset.order;go("orderDetail")});}
$$("[data-order-filter]").forEach(b=>b.onclick=()=>{orderFilter=b.dataset.orderFilter;$$("[data-order-filter]").forEach(x=>x.classList.toggle("active",x===b));renderOrders();});
function renderOrderDetail(){const x=orders.find(o=>o.id===detailId);if(!x)return;const e=equip(x.equipmentId);$("#detailTitle").textContent=e?.name||"Orden";$("#orderDetail").innerHTML=`<article class="detail-card"><span class="badge">${esc(x.type)}</span><h3>${esc(x.description)}</h3><p><b>Equipo:</b> ${esc(e?.code||"")} · ${esc(e?.name||"")}</p><p><b>Prioridad:</b> ${esc(x.priority)} · <b>Estado:</b> ${esc(x.status)}</p><p><b>Técnico:</b> ${esc(x.technician||"Sin asignar")} · <b>Fecha límite:</b> ${fmtDate(x.dueDate)}</p><p><b>Impacto:</b> ${esc(x.impact||"Sin indicar")}</p>${x.photo?`<img class="detail-image" src="${x.photo}">`:""}${x.closedAt?`<hr><p><b>Solución:</b> ${esc(x.resolution)}</p><p><b>Repuestos:</b> ${esc(x.parts||"Ninguno")}</p><p><b>Coste total:</b> ${money(Number(x.laborCost)+Number(x.partsCost))}</p>`:""}</article>`;$("#closeOrderForm").classList.toggle("hidden",!!x.closedAt);}
$("#closeOrderForm").onsubmit=async e=>{e.preventDefault();const x=orders.find(o=>o.id===detailId);if(!x)return;const form=e.currentTarget,d=Object.fromEntries(new FormData(form));delete d.photo;Object.assign(x,d,{finalPhoto:await fileData(form.elements.photo),status:"Finalizada",closedAt:new Date().toISOString()});save();toast("Orden finalizada y registrada");renderOrderDetail();};
function renderPlans(){const rows=[...plans].sort((a,b)=>a.nextDate.localeCompare(b.nextDate));$("#planList").innerHTML=rows.length?rows.map(x=>{const e=equip(x.equipmentId),d=days(x.nextDate);return`<article class="row"><div><b>${esc(x.title)}</b><small>${esc(e?.name||"Equipo")} · ${fmtDate(x.nextDate)} · ${esc(x.technician||"Sin asignar")}</small></div><span class="badge ${d<0?"danger":d<=7?"warning":""}">${d<0?"Vencido":d===0?"Hoy":`${d} días`}</span><button class="mini danger-btn" data-delete-plan="${x.id}">×</button></article>`}).join(""):empty("Crea planes semanales, mensuales o anuales.");$$("[data-delete-plan]").forEach(b=>b.onclick=()=>{if(confirm("¿Eliminar este plan?")){plans=plans.filter(x=>x.id!==b.dataset.deletePlan);save();}});}
function renderCalendar(){const rows=[...plans].sort((a,b)=>a.nextDate.localeCompare(b.nextDate));$("#calendarList").innerHTML=rows.length?rows.map(x=>`<article><time>${fmtDate(x.nextDate)}</time><div><b>${esc(x.title)}</b><small>${esc(equip(x.equipmentId)?.name||"Equipo")} · ${esc(x.technician||"Sin asignar")}</small></div></article>`).join(""):empty("No hay mantenimientos programados.");}
function renderTeam(){$("#teamSummary").innerHTML=`<b>${team.length} de 3 técnicos</b>`;$("#teamList").innerHTML=team.length?team.map(x=>`<article class="row"><div><b>${esc(x.name)}</b><small>${esc(x.email)} · ${esc(x.role)}</small></div><button class="mini danger-btn" data-remove-team="${x.id}">×</button></article>`).join(""):empty("Todavía no hay técnicos invitados.");$("#teamForm").classList.toggle("hidden",team.length>=3);$$("[data-remove-team]").forEach(b=>b.onclick=()=>{team=team.filter(x=>x.id!==b.dataset.removeTeam);save();});}
const diagnosticAreas={
mechanical:{title:"Mecánica y transmisión",causes:["Desalineación, holgura o fijaciones deficientes","Rodamiento, acoplamiento, correa o elemento móvil desgastado","Lubricación incorrecta, insuficiente o contaminada"],checks:["Inspeccionar anclajes, protecciones y elementos visibles con el equipo aislado","Comprobar alineación, holguras y estado de rodamientos o transmisión","Revisar el plan, tipo y cantidad de lubricante indicados por el fabricante"],tools:["Linterna y espejo de inspección","Llaves y útiles autorizados","Medidor de vibraciones o temperatura, si está disponible"],preventive:"Inspección mecánica, apriete, alineación y lubricación"},
electrical:{title:"Electricidad y accionamiento",causes:["Fallo de alimentación, protección o conexión","Sobrecarga, desequilibrio de fases o aislamiento deteriorado","Contactor, variador, motor o cableado con anomalía"],checks:["Revisar alarmas e historial sin anular protecciones","Con personal autorizado, verificar alimentación, protecciones y conexiones","Comparar intensidad, tensión y temperatura con los valores nominales"],tools:["Multímetro homologado","Pinza amperimétrica","Cámara térmica, si está disponible"],preventive:"Revisión eléctrica, apriete, consumos y termografía"},
fluid:{title:"Bombas, presión y fugas",causes:["Obstrucción, entrada de aire o cebado insuficiente","Sello, junta, manguera o válvula deteriorada","Cavitación, giro incorrecto o condición de proceso fuera de rango"],checks:["Aislar presión y temperatura antes de inspeccionar","Revisar fugas visibles, nivel, filtros, válvulas y sentido de flujo","Comparar presiones de aspiración e impulsión con el funcionamiento normal"],tools:["Manómetro adecuado al rango","Linterna y material absorbente autorizado","Útiles de juntas y sellos especificados"],preventive:"Revisión de fugas, filtros, sellos, válvulas y presiones"},
temperature:{title:"Temperatura y refrigeración",causes:["Ventilación, intercambio térmico o caudal insuficiente","Sensor descalibrado o mala transmisión térmica","Sobrecarga, suciedad o condición ambiental elevada"],checks:["Comparar la lectura con un instrumento verificado","Revisar ventiladores, filtros, intercambiadores y circulación sin retirar protecciones en marcha","Comprobar consignas, alarmas y tendencia histórica"],tools:["Termómetro de contacto verificado","Cámara térmica","Material de limpieza autorizado"],preventive:"Control de temperaturas, limpieza e inspección de refrigeración"},
instrumentation:{title:"Sensores e instrumentación",causes:["Sensor sucio, desajustado o fuera de calibración","Cableado, conector o alimentación inestable","Escala, configuración o punto de montaje incorrecto"],checks:["Comparar con un patrón o instrumento de referencia","Revisar montaje, limpieza, conectores y alimentación con personal autorizado","Confirmar escala, unidades, límites y fecha de calibración"],tools:["Patrón o instrumento de referencia","Multímetro o calibrador de proceso","Material de limpieza compatible"],preventive:"Verificación y calibración de sensores e instrumentos"}
};
function detectArea(text,selected){if(selected!=="auto")return selected;const t=text.toLowerCase();if(/fuga|presi[oó]n|bomba|caudal|v[aá]lvula|cavita|gote/.test(t))return"fluid";if(/temperatura|calienta|calor|fr[ií]o|enfr[ií]a|sobrecal/.test(t))return"temperature";if(/el[eé]ctric|tensi[oó]n|corriente|motor|variador|fusible|salta|cable/.test(t))return"electrical";if(/sensor|sonda|lectura|señal|calibra|transmisor/.test(t))return"instrumentation";return"mechanical";}
function severity(impact,text){if(impact==="critical"||/humo|fuego|chispa|quemado|explosi|persona|atrap|producto contamin/.test(text.toLowerCase()))return{label:"DETENER Y AISLAR",className:"danger",priority:"Urgente",warning:"Existe un posible riesgo. No continúes la marcha ni anules protecciones. Aplica el procedimiento de parada, bloqueo y aviso a personal cualificado."};if(impact==="high")return{label:"PRIORIDAD ALTA",className:"warning",priority:"Alta",warning:"Mantén el equipo fuera de servicio hasta realizar una comprobación segura y documentada."};return{label:"REVISIÓN PROGRAMADA",className:"done",priority:"Normal",warning:"Vigila la evolución y programa la revisión sin posponerla si empeoran los síntomas."};}
let lastAssistantDiagnosis=null;
$("#assistantForm").onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget)),area=detectArea(d.symptoms,d.area),data=diagnosticAreas[area],risk=severity(d.impact,d.symptoms),machine=equip(d.equipmentId);lastAssistantDiagnosis={...d,area,data,risk,machine};const list=items=>`<ul>${items.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`;$("#assistantResult").innerHTML=`<article class="card ai-diagnosis"><div class="ai-result-head"><div><p class="eyebrow">ORIENTACIÓN TÉCNICA</p><h3>${esc(data.title)}</h3></div><span class="badge ${risk.className}">${risk.label}</span></div><p class="risk-warning">${esc(risk.warning)}</p><div class="diagnostic-grid"><section><h4>Causas probables</h4>${list(data.causes)}</section><section><h4>Comprobaciones recomendadas</h4>${list(data.checks)}</section><section><h4>Herramientas orientativas</h4>${list(data.tools)}</section><section><h4>Acción preventiva</h4><p>${esc(data.preventive)}</p></section></div><div class="ai-buttons"><button class="btn primary" id="assistantCreateOrder">Crear orden</button><button class="btn" id="assistantCreatePlan">Crear preventivo</button></div><small class="privacy-note">Resultado orientativo basado en reglas técnicas. Respeta siempre bloqueo, etiquetado, permisos de trabajo y manual del fabricante.</small></article>`;$("#assistantResult").classList.remove("hidden");$("#assistantCreateOrder").onclick=createOrderFromAssistant;$("#assistantCreatePlan").onclick=createPlanFromAssistant;};
function createOrderFromAssistant(){const x=lastAssistantDiagnosis;if(!x)return;if(!x.equipmentId)return toast("Selecciona primero un equipo registrado");orders.unshift({id:uid(),equipmentId:x.equipmentId,description:x.symptoms,priority:x.risk.priority,status:"Pendiente",technician:"",dueDate:"",impact:x.impact,type:"Correctivo · Asistente",createdAt:new Date().toISOString(),closedAt:"",resolution:"",parts:"",laborCost:0,partsCost:0});save();toast("Orden creada desde el diagnóstico");go("orders");}
function createPlanFromAssistant(){const x=lastAssistantDiagnosis;if(!x)return;if(!x.equipmentId)return toast("Selecciona primero un equipo registrado");const next=new Date();next.setDate(next.getDate()+30);plans.unshift({id:uid(),equipmentId:x.equipmentId,title:x.data.preventive,frequency:"30",nextDate:next.toISOString().slice(0,10),technician:"",createdAt:new Date().toISOString()});save();toast("Preventivo mensual creado");go("plans");}
function renderAll(){renderMetrics();renderEquipment($("#equipmentSearch")?.value||"");fillEquipmentSelects();renderOrders();renderPlans();renderCalendar();renderTeam();renderOrderDetail();}

function exportXlsx(rows,name,sheet){if(!rows.length)return toast("No hay datos para exportar");const ws=XLSX.utils.json_to_sheet(rows);ws["!cols"]=Object.keys(rows[0]).map(k=>({wch:Math.max(15,k.length+3)}));ws["!autofilter"]={ref:ws["!ref"]};const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,sheet);XLSX.writeFile(wb,name);toast("Informe Excel generado");}
$("#exportEquipment").onclick=()=>exportXlsx(equipment.map(x=>({Código:x.code,Equipo:x.name,Categoría:x.category,Fabricante:x.manufacturer,Modelo:x.model,Serie:x.serial,Centro:x.site,Zona:x.area,Ubicación:x.location,Criticidad:x.criticality,Estado:x.status,Horas:x.hours,Responsable:x.responsible})),"MaintenPro_Equipos.xlsx","Equipos");
$("#exportOrders").onclick=()=>exportXlsx(orders.map(x=>({Equipo:equip(x.equipmentId)?.name,Tipo:x.type,Avería:x.description,Prioridad:x.priority,Estado:x.status,Técnico:x.technician,Límite:x.dueDate,Cierre:x.closedAt,Solución:x.resolution,Repuestos:x.parts,ManoObra:Number(x.laborCost||0),CosteRepuestos:Number(x.partsCost||0)})),"MaintenPro_Ordenes.xlsx","Órdenes");
$("#exportPlans").onclick=()=>exportXlsx(plans.map(x=>({Equipo:equip(x.equipmentId)?.name,Tarea:x.title,Frecuencia_días:x.frequency,Próxima_fecha:x.nextDate,Técnico:x.technician})),"MaintenPro_Preventivos.xlsx","Preventivos");
$("#settingsForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);settings={...settings,...Object.fromEntries(f),notifications:f.has("notifications")};localStorage.setItem("maintenpro.settings",JSON.stringify(settings));applySettings();toast("Configuración guardada");back();};
function applySettings(){$("#appName").textContent=settings.appName||"MaintenPro";const f=$("#settingsForm");Object.entries(settings).forEach(([k,v])=>{if(!f.elements[k])return;f.elements[k].type==="checkbox"?f.elements[k].checked=!!v:f.elements[k].value=v;});const symbol=new Intl.NumberFormat(settings.language,{style:"currency",currency:settings.currency}).formatToParts(0).find(x=>x.type==="currency")?.value||"€";$$(".currency").forEach(x=>x.textContent=symbol);$("#driveStatus").textContent=settings.driveName?`Conectado: ${settings.driveName} · ${settings.ownerEmail}`:"Drive pendiente de conectar.";}
$("#backup").onclick=()=>{const content=JSON.stringify({version:2,exportedAt:new Date().toISOString(),equipment,orders,plans,team,settings},null,2);if(android()?.saveBackup&&settings.driveName&&android().saveBackup(`MaintenPro_Copia_${new Date().toISOString().slice(0,10)}.json`,content))return toast("Copia guardada en Drive");const blob=new Blob([content],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="MaintenPro_Copia.json";a.click();URL.revokeObjectURL(a.href);toast("Copia descargada");};
applySettings();renderAll();go("home",false);if(android()?.checkSubscription){android().checkSubscription();}else{$("#subscriptionPrice").textContent="4,99 € al mes";$("#paywall").classList.remove("hidden");}
