(()=>{
const KEY='moments.planner.v2';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
const current=()=>read().find(p=>p.id===(localStorage.getItem('moments.current')||''));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const templates={corporate:['Acreditación y recepción','Prueba audiovisual y micros','Briefing de ponentes','Coffee break / catering','Control de accesos','Fotografía y prensa','Cierre y desmontaje'],conference:['Registro de asistentes','Prueba de escenario y streaming','Recepción de ponentes','Bloques de ponencias','Pausas y catering','Preguntas y networking','Desmontaje técnico'],communion:['Recepción de familia e invitados','Fotografía de llegada','Cóctel de bienvenida','Servicio de comida','Animación infantil','Tarta y regalos','Despedida y transporte'],birthday:['Montaje de decoración','Recepción de invitados','Catering y bebidas','Animación / música','Tarta','Photocall y regalos','Desmontaje'],gala:['Acreditación / bienvenida','Photocall','Cóctel','Apertura de sala','Cena / servicio','Discursos y premios','Música / cierre'],fair:['Montaje de stands','Acreditaciones','Revisión electricidad y red','Apertura al público','Catering de personal','Control de aforo','Cierre y desmontaje'],default:['Montaje y revisión del recinto','Recepción de proveedores','Apertura / recepción de asistentes','Servicio principal','Momentos clave y fotografía','Cierre de asistentes','Desmontaje y entrega del recinto']};
function kind(p){const t=(p.eventType||p.name||'').toLowerCase();if(/empresa|corpor|presenta/.test(t))return'corporate';if(/congreso|conferencia|convencion/.test(t))return'conference';if(/comunion|bautizo/.test(t))return'communion';if(/cumple/.test(t))return'birthday';if(/gala|premio/.test(t))return'gala';if(/feria|expo/.test(t))return'fair';return'default'}
function inject(){const p=current();if(!p||p.type!=='event')return;const dash=document.querySelector('#dashboardActions');if(!dash||dash.querySelector('[data-events-pro]'))return;const b=document.createElement('button');b.className='action pro-action';b.dataset.eventsPro='1';b.innerHTML='<span class="pro-icon">★</span><b>Evento PRO</b><small>Operaciones, montaje, accesos y control técnico</small>';b.onclick=()=>openPanel();dash.appendChild(b)}
function openPanel(){const p=current();if(!p)return;const active=(p.guests||[]).filter(g=>g.status!=='declined').reduce((a,g)=>a+Number(g.seats||1),0),confirmed=(p.guests||[]).filter(g=>g.status==='confirmed').reduce((a,g)=>a+Number(g.seats||1),0),booked=(p.vendors||[]).filter(v=>v.status==='booked').length,open=(p.tasks||[]).filter(t=>!t.done).length;const checks=[['Aforo y asistentes',active?`${confirmed}/${active} confirmados`:'Sin asistentes cargados',!!active],['Producción técnica',(p.vendors||[]).some(v=>/sonido|audio|tecn|ilumina|video/i.test(v.service||''))?'Proveedor técnico registrado':'Revisar sonido, iluminación, pantallas y corriente',false],['Accesos y acreditación',p.contingency?.operations?'Operativa registrada':'Definir entradas, acreditaciones, VIP y personal',!!p.contingency?.operations],['Seguridad y emergencias',p.contingency?.emergencyContact?'Contacto crítico registrado':'Falta contacto crítico',!!p.contingency?.emergencyContact],['Proveedores',`${booked} contratados`,booked>=3],['Tareas',`${open} pendientes`,open===0]];const m=document.createElement('div');m.className='pro-modal';m.innerHTML=`<div class="pro-modal-card events-pro-card"><p class="eyebrow">CENTRO DE OPERACIONES</p><h2>${esc(p.name)}</h2><p class="lead">Control profesional para eventos: producción, asistentes, accesos, seguridad, montaje y desmontaje.</p><div class="event-kpis"><span><b>${active}</b> asistentes</span><span><b>${booked}</b> proveedores</span><span><b>${open}</b> tareas</span></div><div class="simulation-list">${checks.map((x,i)=>`<article class="${x[2]?'event-ok':'event-warn'}"><b>${x[2]?'✓':'!'}</b><div><strong>${x[0]}</strong><small>${x[1]}</small></div></article>`).join('')}</div><button id="eventTemplate" class="btn primary wide">Crear cronograma profesional</button><button id="eventClose" class="btn wide">Cerrar</button></div>`;document.body.appendChild(m);m.querySelector('#eventClose').onclick=()=>m.remove();m.querySelector('#eventTemplate').onclick=()=>{createTemplate();m.remove()}}
function createTemplate(){const ps=read(),p=ps.find(x=>x.id===(localStorage.getItem('moments.current')||''));if(!p)return;const list=templates[kind(p)],times=['08:00','09:00','10:00','12:00','14:00','18:00','21:00'];p.schedule=p.schedule||[];const existing=new Set(p.schedule.map(x=>(x.title||'').toLowerCase()));list.forEach((title,i)=>{if(!existing.has(title.toLowerCase()))p.schedule.push({id:'evt-'+Date.now()+'-'+i,time:times[i]||'20:00',endTime:'',title,place:p.venue||'',responsible:'',createdAt:new Date().toISOString()})});localStorage.setItem(KEY,JSON.stringify(ps));alert('Cronograma profesional añadido. Puedes ajustar horarios y responsables desde Agenda del día.');location.reload()}
const obs=new MutationObserver(()=>inject());obs.observe(document.body,{subtree:true,childList:true});document.addEventListener('click',()=>setTimeout(inject,30));setTimeout(inject,250);
})();