(()=>{
const PROJECT_KEY="moments.planner.v2",LAYOUT_KEY="moments.floorplans.v3";
const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f));}catch{return f}};
const projects=()=>read(PROJECT_KEY,[]), currentId=()=>localStorage.getItem("moments.current")||"", current=()=>projects().find(p=>p.id===currentId());
let layouts=read(LAYOUT_KEY,{}), selected="", zoom=.42, dragging=null;
const defaults=()=>({width:30,height:20,grid:1,objects:[
{id:"venue-stage",kind:"stage",label:"Escenario",x:12,y:1,w:6,h:2.2},{id:"venue-dance",kind:"dance",label:"Pista de baile",x:11,y:8,w:8,h:5},{id:"venue-bar",kind:"bar",label:"Barra",x:1,y:15.5,w:5,h:2},{id:"venue-dj",kind:"dj",label:"DJ / Sonido",x:24,y:1,w:4,h:2},{id:"venue-photo",kind:"photo",label:"Photocall",x:24,y:15.5,w:4,h:2},{id:"venue-entry",kind:"entry",label:"Entrada",x:13,y:18.2,w:4,h:1.3}],tables:{}});
function layout(){const id=currentId();if(!layouts[id])layouts[id]=defaults();return layouts[id];}
function saveLayout(){layouts[currentId()]=layout();localStorage.setItem(LAYOUT_KEY,JSON.stringify(layouts));}
function syncTables(){const p=current();if(!p)return;const l=layout();const live=new Set(p.tables.map(t=>t.id));Object.keys(l.tables).forEach(id=>{if(!live.has(id))delete l.tables[id]});p.tables.forEach((t,i)=>{if(!l.tables[t.id]){const col=i%5,row=Math.floor(i/5);l.tables[t.id]={x:2+col*5.5,y:3.8+row*5.2,shape:"round",w:2.4,h:2.4,rotation:0};}});saveLayout();}
function inject(){const screen=document.querySelector('[data-screen="tables"]');if(!screen||screen.querySelector("#proFloorplan"))return;
const lead=screen.querySelector(".lead");const wrap=document.createElement("div");wrap.id="proFloorplan";wrap.innerHTML=`
<div class="planner-head"><div><p class="eyebrow">PLANO PROFESIONAL DEL SALÓN</p><h3>Diseña el espacio a escala</h3><p class="lead">Salón amplio con zoom y desplazamiento. Mueve mesas, pista, escenario y servicios con el dedo. Las mesas se muestran con sus sillas reales.</p></div><button id="autoArrange" class="btn primary" type="button">Distribuir automáticamente</button></div>
<div class="planner-toolbar"><label>Ancho (m)<input id="roomW" type="number" min="10" max="100" step="1"></label><label>Fondo (m)<input id="roomH" type="number" min="8" max="80" step="1"></label><label>Zoom<input id="roomZoom" type="range" min="22" max="90" value="42"></label><button id="fitRoom" class="btn" type="button">Encajar</button><button id="addVenueObject" class="btn" type="button">+ Elemento</button></div>
<div class="planner-status" id="plannerStatus"></div>
<div class="room-scroll" id="roomScroll"><div class="room" id="roomCanvas"></div></div>
<div class="object-editor" id="objectEditor"><b>Selecciona una mesa o elemento del plano</b><small>Podrás cambiar forma, tamaño, giro y posición.</small></div>
<div class="planner-legend"><span>● Mesa redonda</span><span>▭ Mesa rectangular</span><span>▰ Imperial</span><span>▦ Pista</span><span>▱ Escenario</span><span>◆ Servicios</span></div>`;
lead.insertAdjacentElement("afterend",wrap);bind();syncTables();render();}
function dims(o){return {w:Math.max(.8,Number(o.w||2.4)),h:Math.max(.8,Number(o.h||2.4))}}
function seatDots(cap,shape){cap=Math.min(20,Math.max(1,Number(cap||0)));return Array.from({length:cap},(_,i)=>{const a=(i/cap)*Math.PI*2;if(shape==="round"){const x=50+47*Math.cos(a),y=50+47*Math.sin(a);return `<i class="seat" style="left:${x}%;top:${y}%"></i>`}const side=i%4,pos=(Math.floor(i/4)+1)/(Math.ceil(cap/4)+1)*100;let x=50,y=50;if(side===0){x=pos;y=-7}else if(side===1){x=107;y=pos}else if(side===2){x=100-pos;y=107}else{x=-7;y=100-pos}return `<i class="seat" style="left:${x}%;top:${y}%"></i>`}).join("")}
function render(){const p=current(),l=layout(),canvas=$("#roomCanvas");if(!p||!canvas)return;syncTables();zoom=Number($("#roomZoom")?.value||42)/100;canvas.style.width=(l.width*100*zoom)+"px";canvas.style.height=(l.height*100*zoom)+"px";canvas.style.setProperty("--meter",100*zoom+"px");
const objs=l.objects.map(o=>objectHtml(o,false)).join("");const tables=p.tables.map(t=>objectHtml({...l.tables[t.id],id:t.id,kind:"table",label:t.name,capacity:t.capacity},true)).join("");canvas.innerHTML=`<div class="room-label">${esc(p.venue||"Salón del evento")} · ${l.width} × ${l.height} m</div>${objs}${tables}`;
canvas.querySelectorAll(".floor-object").forEach(el=>{el.onpointerdown=startDrag;el.onclick=e=>{e.stopPropagation();selected=el.dataset.id;renderEditor();highlight();}});canvas.onclick=()=>{selected="";renderEditor();highlight()};
$("#roomW").value=l.width;$("#roomH").value=l.height;status();renderEditor();highlight();}
function objectHtml(o,isTable){const d=dims(o),x=Number(o.x||0),y=Number(o.y||0),shape=o.shape||"rect",cls=isTable?`table-object ${shape}`:`venue-object ${o.kind}`;const p=current();let meta="";if(isTable){const assigned=(p?.guests||[]).filter(g=>g.tableId===o.id&&g.status!=="declined").reduce((a,g)=>a+Number(g.seats||1),0);meta=`<small>${assigned}/${Number(o.capacity||0)}</small>${seatDots(o.capacity,shape)}`}
return `<div class="floor-object ${cls}" data-id="${esc(o.id)}" style="left:${x*100*zoom}px;top:${y*100*zoom}px;width:${d.w*100*zoom}px;height:${d.h*100*zoom}px;transform:rotate(${Number(o.rotation||0)}deg)"><div class="object-face"><b>${esc(o.label)}</b>${meta}</div></div>`}
function findObj(id){const l=layout();if(l.tables[id])return l.tables[id];return l.objects.find(x=>x.id===id)}
function startDrag(e){e.preventDefault();e.currentTarget.setPointerCapture?.(e.pointerId);selected=e.currentTarget.dataset.id;const o=findObj(selected);if(!o)return;dragging={el:e.currentTarget,o,startX:e.clientX,startY:e.clientY,x:Number(o.x||0),y:Number(o.y||0)};e.currentTarget.onpointermove=moveDrag;e.currentTarget.onpointerup=endDrag;e.currentTarget.onpointercancel=endDrag;highlight();renderEditor();}
function moveDrag(e){if(!dragging)return;const l=layout(),d=dims(dragging.o);let x=dragging.x+(e.clientX-dragging.startX)/(100*zoom),y=dragging.y+(e.clientY-dragging.startY)/(100*zoom);x=Math.max(0,Math.min(l.width-d.w,x));y=Math.max(0,Math.min(l.height-d.h,y));dragging.o.x=Math.round(x*10)/10;dragging.o.y=Math.round(y*10)/10;dragging.el.style.left=dragging.o.x*100*zoom+"px";dragging.el.style.top=dragging.o.y*100*zoom+"px";}
function endDrag(){if(!dragging)return;saveLayout();dragging.el.onpointermove=null;dragging.el.onpointerup=null;dragging=null;status();renderEditor();}
function highlight(){document.querySelectorAll(".floor-object").forEach(x=>x.classList.toggle("selected",x.dataset.id===selected))}
function renderEditor(){const box=$("#objectEditor");if(!box)return;if(!selected){box.innerHTML='<b>Selecciona una mesa o elemento del plano</b><small>Podrás cambiar forma, tamaño, giro y posición.</small>';return}const o=findObj(selected);if(!o)return;const p=current(),t=p?.tables?.find(x=>x.id===selected),isTable=!!t;box.innerHTML=`<div><b>${esc(t?.name||o.label||"Elemento")}</b><small>${isTable?"Mesa del banquete":"Elemento del salón"}</small></div>${isTable?`<label>Forma<select id="editShape"><option value="round">Redonda</option><option value="rect">Rectangular</option><option value="imperial">Imperial</option></select></label>`:""}<label>Ancho m<input id="editW" type="number" min=".8" max="12" step=".2" value="${Number(o.w||2.4)}"></label><label>Fondo m<input id="editH" type="number" min=".8" max="12" step=".2" value="${Number(o.h||2.4)}"></label><label>Giro °<input id="editRot" type="range" min="0" max="345" step="15" value="${Number(o.rotation||0)}"></label>${!isTable?'<button id="removeObj" class="btn danger-btn" type="button">Quitar</button>':''}`;if(isTable){$("#editShape").value=o.shape||"round";$("#editShape").onchange=e=>{o.shape=e.target.value;if(o.shape==="round"){o.w=o.h=Math.max(2.2,Math.min(o.w||2.4,o.h||2.4))}else if(o.shape==="imperial"){o.w=Math.max(5,o.w||5);o.h=Math.max(1.4,o.h||1.6)}saveLayout();render()}}
[["#editW","w"],["#editH","h"],["#editRot","rotation"]].forEach(([s,k])=>{$(s).oninput=e=>{o[k]=Number(e.target.value);saveLayout();renderCanvasOnly()}});if($("#removeObj"))$("#removeObj").onclick=()=>{layout().objects=layout().objects.filter(x=>x.id!==selected);selected="";saveLayout();render()};}
function renderCanvasOnly(){const p=current(),l=layout(),canvas=$("#roomCanvas");if(!p||!canvas)return;canvas.querySelectorAll(".floor-object").forEach(el=>{const o=findObj(el.dataset.id);if(!o)return;const d=dims(o);el.style.left=Number(o.x||0)*100*zoom+"px";el.style.top=Number(o.y||0)*100*zoom+"px";el.style.width=d.w*100*zoom+"px";el.style.height=d.h*100*zoom+"px";el.style.transform=`rotate(${Number(o.rotation||0)}deg)`});}
function autoArrange(){const p=current(),l=layout();if(!p?.tables?.length)return alert("Primero crea las mesas.");const reservedTop=3.5,reservedBottom=3.2,usableH=l.height-reservedTop-reservedBottom;const count=p.tables.length,cols=Math.max(3,Math.min(6,Math.ceil(Math.sqrt(count*l.width/Math.max(usableH,1))))),rows=Math.ceil(count/cols),cellW=l.width/cols,cellH=usableH/rows;p.tables.forEach((t,i)=>{const o=l.tables[t.id],c=i%cols,r=Math.floor(i/cols),size=Math.max(1.8,Math.min(2.7,Math.min(cellW*.55,cellH*.55)));o.shape=o.shape||"round";if(o.shape==="round")o.w=o.h=size;else{o.w=Math.max(2.8,Math.min(cellW*.72,4.2));o.h=Math.max(1.4,Math.min(cellH*.42,2))}o.x=c*cellW+(cellW-o.w)/2;o.y=reservedTop+r*cellH+(cellH-o.h)/2;o.rotation=0});saveLayout();render();}
function status(){const p=current(),l=layout(),box=$("#plannerStatus");if(!p||!box)return;const seats=p.tables.reduce((a,t)=>a+Number(t.capacity||0),0),assigned=p.guests.filter(g=>g.status!=="declined"&&g.tableId).reduce((a,g)=>a+Number(g.seats||1),0),unassigned=p.guests.filter(g=>g.status!=="declined"&&!g.tableId).reduce((a,g)=>a+Number(g.seats||1),0);box.innerHTML=`<span><b>${p.tables.length}</b> mesas</span><span><b>${seats}</b> plazas</span><span><b>${assigned}</b> asignadas</span><span class="${unassigned?"warn":"ok"}"><b>${unassigned}</b> sin mesa</span><span><b>${l.width*l.height}</b> m²</span>`}
function bind(){const l=layout();$("#roomW").value=l.width;$("#roomH").value=l.height;$("#roomZoom").oninput=e=>{zoom=Number(e.target.value)/100;render()};$("#roomW").onchange=e=>{l.width=Math.max(10,Number(e.target.value||30));saveLayout();render()};$("#roomH").onchange=e=>{l.height=Math.max(8,Number(e.target.value||20));saveLayout();render()};$("#autoArrange").onclick=autoArrange;$("#fitRoom").onclick=()=>{$("#roomZoom").value=window.innerWidth<600?28:42;render()};$("#addVenueObject").onclick=()=>{const label=prompt("Elemento: barra, mesa de regalos, columna, zona infantil, buffet...");if(!label)return;layout().objects.push({id:"venue-"+Date.now(),kind:"custom",label,x:2,y:2,w:3,h:1.5,rotation:0});saveLayout();render()};}
function simulation(){const p=current();if(!p)return;const l=layout(),active=p.guests.filter(g=>g.status!=="declined"),unassigned=active.filter(g=>!g.tableId).reduce((a,g)=>a+Number(g.seats||1),0),over=p.tables.filter(t=>active.filter(g=>g.tableId===t.id).reduce((a,g)=>a+Number(g.seats||1),0)>Number(t.capacity||0)),open=(p.tasks||[]).filter(t=>!t.done),unbooked=(p.vendors||[]).filter(v=>v.status!=="booked"),due=(p.expenses||[]).filter(x=>Number(x.amount||0)>Number(x.paid||0));const issues=[];if(unassigned)issues.push(`${unassigned} plazas sin mesa`);if(over.length)issues.push(`${over.length} mesas superan capacidad`);if(open.length)issues.push(`${open.length} tareas pendientes`);if(unbooked.length)issues.push(`${unbooked.length} proveedores aún no contratados`);if(due.length)issues.push(`${due.length} pagos con saldo pendiente`);if((p.schedule||[]).length<5)issues.push("Cronograma del día poco detallado");if(!p.contingency?.planB)issues.push("Falta plan B");const modal=document.createElement("div");modal.className="pro-modal";modal.innerHTML=`<div class="pro-modal-card"><p class="eyebrow">SIMULACIÓN DEL EVENTO</p><h2>${esc(p.name)}</h2><p>Revisión operativa previa al gran día.</p><div class="simulation-score ${issues.length?"warn":"ok"}">${issues.length?`${issues.length} puntos requieren atención`:"Preparado para coordinación final"}</div><div class="simulation-list">${issues.length?issues.map((x,i)=>`<article><b>${i+1}</b><span>${esc(x)}</span></article>`).join(""):'<article><b>✓</b><span>No se detectan bloqueos principales.</span></article>'}</div><p class="lead">Plano: ${l.width} × ${l.height} m · ${p.tables.length} mesas · ${active.reduce((a,g)=>a+Number(g.seats||1),0)} plazas activas.</p><button class="btn primary wide" id="closeSimulation">Cerrar simulación</button></div>`;document.body.append(modal);modal.querySelector("#closeSimulation").onclick=()=>modal.remove();}
function addSimulationButton(){const grid=$("#dashboardActions");if(!grid||grid.querySelector("#simulateEvent"))return;const b=document.createElement("button");b.id="simulateEvent";b.className="action pro-action";b.innerHTML='<span class="pro-icon">▶</span><b>Simular evento</b><small>Detecta fallos antes del gran día</small>';b.onclick=simulation;grid.append(b)}
const observer=new MutationObserver(()=>{inject();addSimulationButton();if(document.querySelector('[data-screen="tables"].active')){syncTables();status()}});observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:["class"]});
window.addEventListener("DOMContentLoaded",()=>{inject();addSimulationButton()});setTimeout(()=>{inject();addSimulationButton()},300);
})();