(()=>{
const PROJECT_KEY='moments.planner.v2',LAYOUT_KEY='moments.floorplans.v4';
const $=s=>document.querySelector(s),read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}},esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const currentId=()=>localStorage.getItem('moments.current')||'',current=()=>read(PROJECT_KEY,[]).find(p=>p.id===currentId());let layouts=read(LAYOUT_KEY,{}),zoom=.32,drag=null,last=false;
const fresh=()=>({width:30,height:20,objects:[{id:'stage',kind:'stage',label:'Escenario',x:11,y:1,w:8,h:2},{id:'dance',kind:'dance',label:'Pista',x:11,y:8,w:8,h:5},{id:'bar',kind:'bar',label:'Barra',x:1,y:16,w:5,h:2},{id:'dj',kind:'dj',label:'DJ',x:25,y:1,w:3,h:2},{id:'entry',kind:'entry',label:'Entrada',x:13,y:18,w:4,h:1.3}],tables:{}}),layout=()=>layouts[currentId()]||(layouts[currentId()]=fresh()),save=()=>{try{localStorage.setItem(LAYOUT_KEY,JSON.stringify(layouts))}catch{}};
function sync(){const p=current(),l=layout(),ts=Array.isArray(p?.tables)?p.tables:[],live=new Set(ts.map(t=>t.id));Object.keys(l.tables).forEach(id=>{if(!live.has(id))delete l.tables[id]});ts.forEach((t,i)=>{if(!l.tables[t.id])l.tables[t.id]={x:2+(i%5)*5.3,y:3.8+Math.floor(i/5)*4.7,w:2.3,h:2.3,shape:'round'}});save()}
function inject(){const s=document.querySelector('[data-screen="tables"]');if(!s?.classList.contains('active')||s.querySelector('#proFloorplan'))return;const lead=s.querySelector('.lead');if(!lead)return;sync();const l=layout(),w=document.createElement('div');w.id='proFloorplan';w.innerHTML=`<div class="planner-head"><div><p class="eyebrow">PLANO PROFESIONAL DEL SALÓN</p><h3>Diseña el espacio a escala</h3><p class="lead">Optimizado para móvil. Mueve mesas y zonas con el dedo.</p></div><button id="autoArrange" class="btn primary">Distribuir</button></div><div class="planner-toolbar"><label>Ancho m<input id="roomW" type="number" value="${l.width}"></label><label>Fondo m<input id="roomH" type="number" value="${l.height}"></label><label>Zoom<input id="roomZoom" type="range" min="22" max="65" value="32"></label></div><div class="planner-status" id="plannerStatus"></div><div class="room-scroll"><div class="room" id="roomCanvas"></div></div>`;lead.insertAdjacentElement('afterend',w);bind();render()}
function render(){const p=current(),l=layout(),c=$('#roomCanvas');if(!p||!c)return;zoom=Number($('#roomZoom')?.value||32)/100;c.style.width=l.width*100*zoom+'px';c.style.height=l.height*100*zoom+'px';c.style.setProperty('--meter',100*zoom+'px');const assigned={};(p.guests||[]).forEach(g=>{if(g.status!=='declined'&&g.tableId)assigned[g.tableId]=(assigned[g.tableId]||0)+Number(g.seats||1)});const one=(o,table=false,t=null)=>`<div class="floor-object ${table?'table-object '+(o.shape||'round'):'venue-object '+o.kind}" data-id="${esc(o.id)}" style="left:${Number(o.x||0)*100*zoom}px;top:${Number(o.y||0)*100*zoom}px;width:${Number(o.w||2.3)*100*zoom}px;height:${Number(o.h||2.3)*100*zoom}px"><div class="object-face"><b>${esc(table?t.name:o.label)}</b>${table?`<small>${assigned[t.id]||0}/${Number(t.capacity||0)}</small>`:''}</div></div>`;c.innerHTML=`<div class="room-label">${esc(p.venue||'Salón')} · ${l.width} × ${l.height} m</div>`+l.objects.map(o=>one(o)).join('')+(p.tables||[]).map(t=>one({...l.tables[t.id],id:t.id},true,t)).join('');c.querySelectorAll('.floor-object').forEach(el=>{el.onpointerdown=start});status()}
function find(id){const l=layout();return l.tables[id]||l.objects.find(x=>x.id===id)}function start(e){e.preventDefault();const o=find(e.currentTarget.dataset.id);if(!o)return;drag={el:e.currentTarget,o,sx:e.clientX,sy:e.clientY,x:Number(o.x||0),y:Number(o.y||0)};try{e.currentTarget.setPointerCapture(e.pointerId)}catch{};e.currentTarget.onpointermove=move;e.currentTarget.onpointerup=end}function move(e){if(!drag)return;const l=layout(),w=Number(drag.o.w||2.3),h=Number(drag.o.h||2.3);drag.o.x=Math.max(0,Math.min(l.width-w,drag.x+(e.clientX-drag.sx)/(100*zoom)));drag.o.y=Math.max(0,Math.min(l.height-h,drag.y+(e.clientY-drag.sy)/(100*zoom)));drag.el.style.left=drag.o.x*100*zoom+'px';drag.el.style.top=drag.o.y*100*zoom+'px'}function end(){if(!drag)return;save();drag.el.onpointermove=null;drag.el.onpointerup=null;drag=null}
function status(){const p=current(),l=layout(),b=$('#plannerStatus');if(!b||!p)return;b.innerHTML=`<span><b>${(p.tables||[]).length}</b> mesas</span><span><b>${(p.tables||[]).reduce((a,t)=>a+Number(t.capacity||0),0)}</b> plazas</span><span><b>${l.width*l.height}</b> m²</span>`}
function arrange(){const p=current(),l=layout(),ts=p?.tables||[];if(!ts.length)return alert('Primero crea las mesas.');const cols=Math.max(2,Math.min(6,Math.ceil(Math.sqrt(ts.length*l.width/l.height)))),rows=Math.ceil(ts.length/cols),cw=l.width/cols,ch=(l.height-6)/rows;ts.forEach((t,i)=>{const o=l.tables[t.id],c=i%cols,r=Math.floor(i/cols);o.w=o.h=Math.max(1.8,Math.min(2.5,cw*.5,ch*.5));o.x=c*cw+(cw-o.w)/2;o.y=3+r*ch+(ch-o.h)/2});save();render()}
function bind(){const l=layout();$('#roomZoom').onchange=e=>{zoom=Number(e.target.value)/100;render()};$('#roomW').onchange=e=>{l.width=Math.max(10,Number(e.target.value||30));save();render()};$('#roomH').onchange=e=>{l.height=Math.max(8,Number(e.target.value||20));save();render()};$('#autoArrange').onclick=arrange}
function watch(){const s=document.querySelector('[data-screen="tables"]'),active=!!s?.classList.contains('active');if(active&&!last)setTimeout(inject,80);if(!active&&last)$('#proFloorplan')?.remove();last=active}const ob=new MutationObserver(watch);ob.observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']});watch();
})();